---
title: 'RMarkdown:  In Class Assignment'
author: "Pukar Kharel"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
```
```
"Wise words" 
Discipline is The Bridge Between Goals And Accomplishmnet - Jim Rohn
```
[link to quote](https://jayodonnell.com/discipline-is-the-bridge-between-goals-and-accomplishment/)

##

"My semester"


*Course Name*    | **Course Number**  | Course Tittle                | *Instructor Name*    |
:-------------   | :-------------     | :--------------------------- | :-----------------
Data 2401        | 21352              | Data Science I               | Professor Katherin   |
CS 1311          | 21312              | Intro to Computing w/ Python | Professor John       |
Math 2305        | 21733              | Discrete Math Struct.        | Professor Vien       |
Math 2421        | 22319              | Differ & Integral Calculus   | Professor Sergiy     |

##

"I recommend" - Akon - is very involved in the community 

Akon
*Sorry, Blame it On Me*



Reminder: There is a "Markdown Help" page available in RStudio. 


## In-class Activity, Markdown

Below the "Your work here" section header, do the following 3 things. To turn this in, knit the RMarkdown file, and zip and submit the html.  

1. Make a subsection called "Wise words". Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

2. Make a subsection called "My semester". Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

+ A _subsubheading_ with the name of the artist or author;    
+ An example of their writing or lyrics (formatted in a *plain code block*);   
+ A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     


Note that you can click "Knit" as you go along to see what the final results are going to look like. **Once you're done, commit the changes and push the repo back to your assignment on GitHub!**
 
